version: '3'

services:
      
  goapp:
    build: 
      dockerfile: ./Dockerfile.prod
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - "8080"
    extra_hosts:
      - "localhost:127.0.0.1"